### ISSUE TITLE
not able to complete a local build

### ISSUE THREAD

**Issue by docfactory37** [flo-mic/docker-mariadb-backup#1]
Hi @flo-mic,

Im trying to build your docker image locally and i get the below error 

![image](https://user-images.githubusercontent.com/20963053/157382364-4b85aaf3-362b-4696-adc5-88d390192170.png)

it looks like it is an issue with the wget in the install scripted.

Hoping you could help me fix the issue.

**Comment by flo-mic** [comment]
@docfactory37  please try again. S6 has upgraded to a new major version v3 which had a breaking change for the installation. This should be fixed now ;)

**Comment by docfactory37** [comment]
@flo-mic i have tested the build again and its working now thank you for you help in fixing the issue.
